### ISSUE TITLE
Add the possibility to visualize the map created with the Folium library

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#115]
One author use Folium, example here https://github.com/jdh-observer/jdh001-8pGzPyTDKBjR/blob/main/JDH_Article.ipynb

https://python-visualization.github.io/folium/quickstart.html

<img width="1087" alt="Screenshot 2021-07-01 at 11 59 13" src="https://user-images.githubusercontent.com/35602279/124106083-2d81d400-da64-11eb-87b1-dd9821c17f30.png">

in the article:

<img width="352" alt="Screenshot 2021-07-01 at 12 03 28" src="https://user-images.githubusercontent.com/35602279/124106332-67eb7100-da64-11eb-9401-58e70ee3b333.png">

**Comment by eliselavy** [comment]
Output is a <div> html

<img width="256" alt="Screenshot 2021-07-01 at 12 09 10" src="https://user-images.githubusercontent.com/35602279/124107102-2effcc00-da65-11eb-9d41-2b4ccc24a933.png">

**Comment by danieleguido** [comment]
The html is basically an iframe.
The message behind the script is `Make this notebook trusted to load map` Can you check @eliselavy 

![Screenshot 2021-07-01 at 15 18 44](https://user-images.githubusercontent.com/1181642/124131115-c40fbe80-da7f-11eb-8528-f6c79390ef04.png)

**Comment by eliselavy** [comment]
simple map available here: https://github.com/C2DH/jdh-notebook/blob/master/examples/use-folium-map.ipynb

the notebook is trusted
<img width="821" alt="Screenshot 2021-07-02 at 16 26 12" src="https://user-images.githubusercontent.com/35602279/124289168-4ec0ee00-db52-11eb-8b26-f262dc88b610.png">

but in the output still the message beofre the iframe
<img width="743" alt="Screenshot 2021-07-02 at 16 27 25" src="https://user-images.githubusercontent.com/35602279/124289311-73b56100-db52-11eb-9fdb-67271fea8bab.png">

**Comment by eliselavy** [comment]
support of "Text/html" added in ArticleCellOutput.js

if (['execute_result', 'display_data'].includes(output.output_type) && output.data['text/html']) {
