### ISSUE TITLE
Set a specific background color to tie the hermeneutics steps

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#132]
Lars Wieneke  12:29 PM
One question: I see the separating lines

but could we do with a specific background color to tie the hermeneutics steps?

**Comment by danieleguido** [comment]
The lines are useful reminders that there is collapsed content, not sure the bg will suffice

**Comment by biumiamy** [comment]
https://github.com/C2DH/journal-of-digital-history/pull/153

**Comment by eliselavy** [comment]
no more relevant with the new display of the hermeneutic layer
