### ISSUE TITLE
Render Markdown quotes in the article

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#142]
Some authors use markdown quotes for the citation

Example here: https://github.com/jdh-observer/jdh001-SLCj9T3MsrEk/blob/main/jdh_twitter5_anonymised.ipynb

<img width="649" alt="Screenshot 2021-07-21 at 16 04 54" src="https://user-images.githubusercontent.com/35602279/126502127-1eb78836-b1e7-45f8-a708-599d05343dd2.png">

<img width="667" alt="Screenshot 2021-07-21 at 16 06 27" src="https://user-images.githubusercontent.com/35602279/126502384-629408c1-7268-4bfd-8688-c5ae0e179e45.png">

**Comment by eliselavy** [comment]
@biumiamy style propositon?

**Comment by danieleguido** [comment]
a `quote` tag?
