### ISSUE TITLE
Loading article: propose abstract - title - contributor to read 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#164]
Loading article: propose abstract - title - contributor to read 

In the backend information available in the JSON field data:

Exemple: http://10.240.4.179/api/articles/4yxHGiqXYRbX/

<img width="1055" alt="Screenshot 2021-08-31 at 10 17 27" src="https://user-images.githubusercontent.com/35602279/131467763-89403547-7c7b-47e0-bedd-67bf64bb29cd.png">

**Comment by danieleguido** [comment]
PR #169 merged in develop, the metadata still to be completed.

**Comment by eliselavy** [comment]
@danieleguido json changed and deployed in dev
 "data": {
        "title": [
            "# Inscriptions as data: digital epigraphy in macro-historical perspective "
        ],
        "abstract": [
            "As short texts written on a durable medium, inscriptions represent invaluable insight into past societies, their organization, cultural norms and practices. Several hundred thousand inscriptions in Greek and Latin language survived until today, providing us with a line of evidence concerning populations of large cities and rural communities of the entire Mediterranean Basin in the period between the eighth century BC and eighth century AD. Although published inscriptions have been near-completely digitized and exist in online databases, and open computational tools exist to handle large datasets, large-scale and comparative studies of inscriptions are still rare. Numerous technical and conceptual issues, such as the inconsistent resolution of spatial and temporal attributes or the incompatibility of data structures between datasets, hinder the aggregation and analysis of thousands of inscriptions. The incomplete, uncertain and complex nature of inscriptions as a historical source required us to develop a series of custom open-source tools and reproducible pipelines, enabling a macro-scale overview of epigraphic production in time and space. To illustrate the potential of quantitative studies in epigraphy, we harvest and render comparable two well-established, yet very distinct, digital collections for Latin epigraphy: *Epigraphic Database Heidelberg (EDH)*, containing over 81,000 records and *Epigraphische Datenbank Clauss-Slaby (EDCS)* with over 500,000 records. Placing the datasets side-by-side, we contrast past interpretations of epigraphic habit based on limited samples with trends derived from all available data and discuss their strengths and shortcomings of each respective dataset. We assert that research communities stand to gain from extending digital infrastructures to reduce barriers to access with packages of open and reusable research tools."
        ],
        "contributor": [
            "### anon",
            [
                "### anon"
            ],
            [
                "### anon"
            ]
        ]
    },

**Comment by eliselavy** [comment]
@danieleguido keywords have been added http://10.240.4.179/api/articles/4yxHGiqXYRbX/ if we want to align preloading and loading:

**Comment by eliselavy** [comment]
<img width="974" alt="Screenshot 2021-09-08 at 09 08 33" src="https://user-images.githubusercontent.com/35602279/132462758-513c11bb-cce3-480a-968b-d3f3c7572a12.png">
<img width="986" alt="Screenshot 2021-09-08 at 09 08 40" src="https://user-images.githubusercontent.com/35602279/132462779-65a5622e-b0d9-436e-bc2e-5fa0cad1e80a.png">
