### ISSUE TITLE
Support of the <sup> tag

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#168]
early 20<sup>th</sup> century 

example following article: http://10.240.4.179/en/article/33pRxE2dtUHP

**Comment by biumiamy** [comment]
Issue remains if mentioned twice in a paragraph (Kinora article)

![2022-04-11 16_26_51-Journal of Digital History](https://user-images.githubusercontent.com/47319502/162761604-26c3bc28-65b8-4b2e-814f-1eb578d3452b.png)

**Comment by biumiamy** [comment]
also not supported in the keywords

![2022-04-11 19_55_49-Journal of Digital History](https://user-images.githubusercontent.com/47319502/162801602-6702feef-8949-41b0-b832-0fd88b79f392.png)

**Comment by salaun-marion** [comment]
Works well inside the article
![Image](https://github.com/user-attachments/assets/1fafa738-ee38-4787-99c7-c4082cb01c3b)

But still not supported inside the tags
![Image](https://github.com/user-attachments/assets/c391ae73-ea35-492a-b117-8ce616992c5c)
→ Needs to be improved inside the tags of the article
