### ISSUE TITLE
Integrate the explanation of the fingerprint

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#189]
Integrate the explanation of the fingerprint

Need to find a dedicated place

**Comment by biumiamy** [comment]
@danieleguido will add a section on the [about page](https://journalofdigitalhistory.org/en/about) and link it to the code showing how it was done as an example

**Comment by biumiamy** [comment]
The first issue editorial will also include the fingerprint video on the hermeneutics layer - besides the code, we could link to that video as well from the about page

**Comment by biumiamy** [comment]
guideline changes need to be added to prod by @danieleguido or @eliselavy

**Comment by danieleguido** [comment]
@biumiamy can we close this ticket?
