### ISSUE TITLE
Redesign header area of article

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#269]
author biography
gallery of figures (/tables?)
fingerprint

move the issue https://github.com/C2DH/jdh-notebook/issues/50 here as it related to front end and not pure notebook

**Comment by biumiamy** [comment]
Design proposal:
https://www.figma.com/file/Om5UWoj9z1IH311IQ9RXWN/JDH-Article?node-id=1646%3A7737

**Comment by biumiamy** [comment]
video: https://digitalhistoryjournal.slack.com/files/UUC7S3NUA/F02JJ8KSDDZ/author_fingerprint_gallery.mp4

**Comment by biumiamy** [comment]
Author header section

![MacBook - 7](https://github.com/C2DH/journal-of-digital-history/assets/47319502/8b5c1646-a62f-4cc7-9e94-6c5e2c2dcc42)

**Comment by biumiamy** [comment]
#447

**Comment by biumiamy** [comment]
add actions to a single place on the top right corner

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/1b694dad-385e-4a6e-971c-943de18bdf18)

when scrolling, the actions stay at the same place and the title is shown as well

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/5d6d282f-09ae-44f5-8006-e58699c65c27)

**Comment by biumiamy** [comment]
Change style of author to look like a button 

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/7774e731-25f3-48fc-a520-590a71d1c572)

**Comment by eliselavy** [comment]
About the play with code button:
a pop-up with some explanation :
how to set up locally
how to launch on a cloud service
how to access the datas / dataverse links

**Comment by biumiamy** [comment]
update: 
- place actions at the top near the headline
- when scrolling the actions move to the right next to the N-/H-buttons and the title of the article is shown
- change N-/H-button switch (but without icon)

![2023-07-24 14_52_07-JDH Article – Figma](https://github.com/C2DH/journal-of-digital-history/assets/47319502/675e1b4d-c948-415a-8a31-7e2ca74df5d2)

![2023-07-24 14_52_19-JDH Article – Figma](https://github.com/C2DH/journal-of-digital-history/assets/47319502/5301de85-6fde-4c67-b6ee-104758ceba69)

**Comment by biumiamy** [comment]
popup is similar to the Release Notes

**Comment by biumiamy** [comment]
The popup shows the three logos for the possible ways to navigate..

The Github one has a speciality as it can either go to the Python or R repo

![Popup_PlaywData_1](https://github.com/C2DH/journal-of-digital-history/assets/47319502/ddd3b178-996a-4561-a4e3-05c26c4ff050)
![Popup_PlaywData_2](https://github.com/C2DH/journal-of-digital-history/assets/47319502/9129ecdb-a0ab-448e-b906-821b3e6b381e)

This only works if we have links of course :)

**Comment by biumiamy** [comment]
and we should align button and title of the popup of course :D Play with Data or Code.. what is better?

**Comment by eliselavy** [comment]
but seems to have indeed differents icons https://iconduck.com/free-icons/dataverse-colored

**Comment by eliselavy** [comment]
@danieleguido to use from the api: http://10.240.4.179/api/articles/L2gBr3BzwH8Z/
field: **dataverse_url** added
**kernel_language** added deducted from the first tag in category tool, can have value:

"kernel_language": "R",
"kernel_language": "python"

**Comment by biumiamy** [comment]
Here's an update
- exchanged logo for dataverse
- added text for better comparison
- added link to the guideline for Github

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/872dd862-a831-491e-b615-272251ff1644)

**Comment by biumiamy** [comment]
Update:


![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/77f7d06c-4495-43dd-9512-082dc3d71bc2)

**Comment by eliselavy** [comment]
In development, problem icon 
to be provided @biumiamy

**Comment by biumiamy** [comment]
icons provided

**Comment by biumiamy** [comment]
aligned buttons

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/a107050f-e15d-4fd7-80ef-199825c2c64b)

**Comment by biumiamy** [comment]
to be tested

**Comment by eliselavy** [comment]
In prod v4.2.2
