### ISSUE TITLE
Notebook Viewer button

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#278]
change spacing in button from text to "link" icon

![2021-10-28 06_55_22-Journal of Digital History](https://user-images.githubusercontent.com/47319502/139189603-604c2ed3-954e-4e41-8a4e-b0f57ed48f10.png)

**Comment by danieleguido** [comment]
Current version:
<img width="990" alt="Screenshot 2022-01-05 at 16 41 48" src="https://user-images.githubusercontent.com/1181642/148245830-b7ef3335-871d-4d04-9960-6498795fbfd5.png">

feel free to reopen this issue :)
