### ISSUE TITLE
Make notebook code interactive

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#280]
Ideally without having to go into binderhub, the user should be able to manipulate some of the code or change scales...

Here's some example of how others are doing it:

from https://bio-protocol.org/eLIFErap61277?item=s4-3 

![2021-11-04 16_39_45-Window](https://user-images.githubusercontent.com/47319502/140365898-2d5d278c-6a2d-45b5-9196-a81a0eab243a.png)

could be like [observerable](https://observablehq.com/)

**Comment by biumiamy** [comment]
sth new: https://www.nbinteract.com/

https://observablehq.com/@danieleguido/jdh-fingerprint

**Comment by danieleguido** [comment]
Add support for https://github.com/executablebooks/thebe ?

**Comment by eliselavy** [comment]
linked also to MyBinder problem https://github.com/C2DH/jdh-notebook/issues/117

**Comment by danieleguido** [comment]
Issue moved to #552
