### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#283]
- summary of all new features per release
- place somewhere on the website

**Comment by danieleguido** [comment]
Hi @biumiamy releases have indeed a special status on github; we can refer to the related github page from the website

**Comment by biumiamy** [comment]
https://changelog.md/
https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c

**Comment by biumiamy** [comment]
@eliselavy 
Yes in the past , used to this sort of things date of the release , what’s news button, popover with all the releases notes.
But as a project hosted on GitHub we can maybe  use the CHANGELOG.md
Philosophy here: https://changelog.md/ 
Example here: https://github.com/standard/standard/blob/master/CHANGELOG.md but promote it with  your design?

**Comment by biumiamy** [comment]
@orielisar 
I think it’s a good idea to have “release notes” or “what’s new” on the journal’s website.
Here is a nice example of how Notion created a human-readable page describing what’s new in each version. Exactly like what Elisabeth shared.
https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c
What I like about Notion is that they curated the changes according to subjects, they’ve added images and animated gifs to describe the changes, they’ve used a ‘human’ language that can be understand by normal people, and they kept the technical terms and stuff that are relevant for the more code-tech savvy people.

**Comment by biumiamy** [comment]
@biumiamy 
I imagined this use case: when the next release is out, how will we inform the authors about the change and what exactly has changed. Could also be a popover on the website.
I never read this stuff when a program has a new release (like in Photoshop or other Adobe products) , so we need to do it in an appealing way that brings value to the user and not make them feel like they are wasting time

**Comment by eliselavy** [comment]
https://github.com/C2DH/journal-of-digital-history/releases/tag/v3.1.0

**Comment by lwieneke** [comment]
Feature implemented (footer)
