### ISSUE TITLE
Fix tooltip content on accordion hover state 

### ISSUE THREAD

**Issue by orielisar** [C2DH/journal-of-digital-history#297]
**Current condition**
1. When hovering over an accordion item on both the narrative and hermeneutics layers, the content of the tool-tip is similar to the accordion item itself. 
<img width="511" alt="Screenshot 2021-11-23 at 10 44 25" src="https://user-images.githubusercontent.com/1911723/143032101-d011412d-4b54-43a0-8b9a-2c463f371d8e.png">
2. When expanding the accordion item, the tooltip says "collapse".
<img width="434" alt="Screenshot 2021-11-23 at 10 44 30" src="https://user-images.githubusercontent.com/1911723/143032196-416ca7dc-0546-485f-a08f-c0c7899397ee.png">

**Desirable condition**
1. The tooltip should say "expand" and "collapse"

**Comment by eliselavy** [comment]
no more relevant as accordeon has been removed
