### ISSUE TITLE
No more difference with APA and MLA style in the citation popup

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#305]
https://www.bibliography.com/mla/apa-vs-mla-citation-page/

The difference between MLA and APA citation is how they are formatting.
 MLA citations include the last name and first name and title in title case. 
APA citations on the other hand, include the author's last name and first initial, title in sentence case, and no period after a URL.

**Comment by danieleguido** [comment]
I removed MLA and added harvard style according to [the default settings of the citation-js library](https://citation.js.org/api/0.3/tutorial-output_formats.html).
Merged in develop https://github.com/C2DH/journal-of-digital-history/pull/307
