### ISSUE TITLE
Interpret markdown in title of the table of contents

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#322]
See example here : http://localhost:3000/en/article/WBqfZzfi7nHK

## Quantifying the *epigraphic habit*, in space and time
<img width="261" alt="Screenshot 2022-01-14 at 16 54 04" src="https://user-images.githubusercontent.com/35602279/149546548-6e8e91fb-d33c-453f-9811-58d9468a3143.png">

**Comment by danieleguido** [comment]
![Screenshot 2022-01-18 at 16 04 14](https://user-images.githubusercontent.com/1181642/149962677-23e99f49-9743-4cf7-8346-a6bd3b17a0f1.png)
