### ISSUE TITLE
Guidelines:  improvment

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#327]
- checklist to provide 
Emphasize the use of the github template repo: 
New url here: https://github.com/C2DH/template_repo_JDH

- citation in bracket
- choose your licence
- [anchor](https://github.com/C2DH/jdh-notebook/issues/49)

**Comment by biumiamy** [comment]
@inactinique :
add multiple ways to install Jupyter Notebook
via anaconda

**Comment by biumiamy** [comment]
try it on [deepnote](https://deepnote.com/) (instead of google collab), but need to try with cite2c

**Comment by eliselavy** [comment]
new way easier to updathe userguide: https://github.com/C2DH/journal-of-digital-history/wiki#how-to-update-the-guidelines-for-authors

**Comment by eliselavy** [comment]
exemple of checklist  here https://jhnr.uni.lu/index.php/jhnr/about/submissions

**Comment by eliselavy** [comment]
@eliselavy need to provide strong version requirement for the cite2c plugin.
it means: cite2c requires jupyter-notebook > 4.2 and jupyter-notebook <= 6.2.0

**Comment by biumiamy** [comment]
- img requirements (72dpi, dimension...) - max. length 1000 px (long edge), 72dpi
- mention BE as language (not just English)? - yes clarify
- cite2c citation (put author in brackets, page no. outside) -> dhdhddh, p.9 (chicago style for authors) ([see reference](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html)) - (open issue for Daniele - regarding citation of website)
- spelling and formatting rules (like formatting the value of a quantity) (what else?) - units of measurements (find website again)
- types of media (img, video, 3d, sound?)
- copyright: placeholder with template example (choose one copyright as proposed in template), (in status review done - mention signing contract via email)
- update template with example of everything ()
- how to use Altair? (as data viz) besides (matplotlib or) bokeh - only links to tutorials (but show: technology we support - check lib on article filters)
- anaconda guide: link to tutorials, but also to delete anaconda. (Elisabeth: 28. April with Andreas - make screenshots & markdown guideline)

**Still to be done:**
- update: figure numbering automatic (tardis)
- plagiarism check (use with pdf version + H-layer - could work with Uni's software)
- spellchecking plugin - for the moment: fail
- gallery (tardis)
- move cite2c to jupyter lab
- jupyter lab: how to find everything (tags, metadata, does parsing work? etc.)

**Comment by biumiamy** [comment]
add: how to install jupyter

**Comment by biumiamy** [comment]
add: "executed jupyter notebook" (why it makes a difference)

**Comment by biumiamy** [comment]
add: video on the how to install Docker to run jupyter based on [this](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/blob/master/docker-desktop-windows.pdf) and [this](https://github.com/C2DH/journal-of-digital-history-jupyter-stack) guide. 
Already tested it [here](https://docs.google.com/document/d/1E4fkUaELoMrRDc8_hCm3abhhzHdXQ2lRkCXzE4kx8Zw/edit)

**Comment by biumiamy** [comment]
Feedback from @inactinique:
- mention the Jupyter Notebook version that is required when using Anaconda:
nbconvert        : 6.0.7
jupyter client   : 6.1.7
jupyter-notebook : 6.2.0 (modifié)
- for now: clone/copy the repo button with notebook template
- long-term plan: perhaps use 2 buttons at the top in the guideline: one for R and Python

**Comment by biumiamy** [comment]
Question:
- how should users invite collaborators to their repo? since the jupyter stack is a clone and they have no writing rights, how can they collaborate?

**Comment by eliselavy** [comment]
If the user use the jupyter-stack, he needs to copy his GitHub repository inside the directory work:
<img width="276" alt="Screenshot 2022-09-01 at 10 04 49" src="https://user-images.githubusercontent.com/35602279/187864292-17a25c88-3f82-440c-ac98-c16f99f8a7b6.png">

**Comment by biumiamy** [comment]
consider another way to present information (if it's short)

![2022-09-08 11_55_00-Window](https://user-images.githubusercontent.com/47319502/189093761-357d76fd-ca70-4fff-bc38-e3dc79ed7887.png)

cell styling: https://github.com/innovationOUtside/nb_extension_tagstyler

**Comment by biumiamy** [comment]
Problem of just showing many figures is not really providing any structure
![2022-09-08 12_04_16-NotificationsWindow](https://user-images.githubusercontent.com/47319502/189095139-d7c78c90-bcd0-4dcb-a3dc-e9ce0e186e04.png)

**Comment by eliselavy** [comment]
@inactinique @biumiamy 

- In Anaconda, just downgrade the notebook library to 6.2.0
![image](https://user-images.githubusercontent.com/35602279/191953756-318ac8b9-ac68-4996-9104-1a2273cc21a6.png)
- With pip

**Comment by eliselavy** [comment]
deploy in tardis v4.0.0
