### ISSUE TITLE
Allow several call of papers at the same time 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#335]
In the home page / in the abstract submission possibility to answer to different CFP.

@inactinique has planned to launch a CFP for a special issue on web history in parallel of the issue jdh002

**Comment by eliselavy** [comment]
[Web History Special Issue Proposal.docx](https://github.com/C2DH/journal-of-digital-history/files/7972550/Web.History.Special.Issue.Proposal.docx)

**Comment by eliselavy** [comment]
- switching hero banner at the top with both call for papers
- dedicated page for the call of paper
- abstract form

**Comment by eliselavy** [comment]
Call of paper available here: https://github.com/C2DH/jdh-notebook/blob/master/cfp/history-of-the-web/history-of-the-web.ipynb

**Comment by biumiamy** [comment]
Design: 
https://www.figma.com/file/vSoSgxR18Sj5gFccxX4Mrj/Journal-Landing-Page?node-id=531%3A182

Video:
https://digitalhistoryjournal.slack.com/archives/G019LKDTNAD/p1643806870918399

**Comment by danieleguido** [comment]
fixed in #359 with Open graph support. see [wiki](https://github.com/C2DH/journal-of-digital-history/wiki) for documentation.
