### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'author')

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#385]
Kinora article not rendered http://10.240.4.179/en/article/33pRxE2dtUHP

react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'author')
    at e.value (ArticleReference.js:46:28)
    at new e (ArticleReference.js:12:30)
    at ipynb.js:75:25
    at String.replace (<anonymous>)
    at O.o.map.forEach.r.sources (ipynb.js:74:6)
    at ipynb.js:281:37
    at Array.forEach (<anonymous>)
    at O (ipynb.js:270:6)
    at i (ipynb.js:14:20)
    at de (Article.js:52:23)

  getAuthorNames(ref) {
    // add editors as authors when there are no authors
    let authorNames = !ref.author && Array.isArray(ref.editor)

**Comment by eliselavy** [comment]
Difference of behaviour between local preview and preview:
https://github.com/C2DH/journal-of-digital-history/issues/309

**Comment by eliselavy** [comment]
To investigate if linked to following problem : https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529#issuecomment-1001053264

**Comment by eliselavy** [comment]
Difference between cite2c local and github:
LOCAL:
 "cite2c": {
   "citations": {
    "7748027/JQXTIMIU": {
     "URL": "https://icaci.org/files/documents/ICC_proceedings/ICC2015/papers/18/145.html",
     "accessed": {
      "day": 12,
      "month": 2,
      "year": 2022
     },
     "author": [
      {
       "family": "Aroom",
       "given": "Jean"
      },
      {
       "family": "Metcalf",
       "given": "Alida"
      },
      {
       "family": "El-dahdah",
       "given": "Farès"
      },
      {
       "family": "Heyman",
       "given": "David"
      }
     ],
     "event": "27th International Cartographic Conference",
     "event-place": "Rio de Janeiro",
     "id": "7748027/JQXTIMIU",
     "issued": {
      "year": 2015
     },
     "publisher-place": "Rio de Janeiro",
     "title": "imagineRio: A Diachronic Atlas of Rio de Janeiro's Social and Architectural Evolution",
     "type": "speech"
    }
   

GITHUB
"cite2c": {
   "citations": {
    "7748027/JQXTIMIU": {
     "URL": "https://icaci.org/files/documents/ICC_proceedings/ICC2015/papers/18/145.html",
     "accessed": {
      "date-parts": [
       [
        2022,
        2,
        12
       ]
      ]
     },
     "author": [
      {
       "family": "Aroom",
       "given": "Jean"
      },
      {
       "family": "Metcalf",
       "given": "Alida"
      },
      {
       "family": "El-dahdah",
       "given": "Farès"
      },
      {
       "family": "Heyman",
       "given": "David"
      }
     ],
     "event": "27th International Cartographic Conference",
     "event-place": "Rio de Janeiro",
     "issued": {
      "date-parts": [
       [
        2015
       ]
      ]
     },
     "publisher-place": "Rio de Janeiro",
     "title": "imagineRio: A Diachronic Atlas of Rio de Janeiro's Social and Architectural Evolution",
     "type": "speech"
    }
   }
  },

**Comment by danieleguido** [comment]
fixed in dev https://github.com/C2DH/journal-of-digital-history/pull/386
