### ISSUE TITLE
Adopt stylesheet for site text

### ISSUE THREAD

**Issue by stakats** [C2DH/journal-of-digital-history#40]
Currently we have a mix of American and British English. Naturally I prefer the former, i.e. "connection" and "rigor" not "connexion" and "rigour", "a historian" not "an historian" etc. It seems like some of the drafters here agree with me, and some don't...

**Comment by danieleguido** [comment]
hi @stakats yes you're right, there's a mix of both. We should adopt the British English as this is a COMM requirements
