### ISSUE TITLE
Create popover when visiting landing page about newest features from Serenity release

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#408]
- create a popover that appears when visiting the landing page / article OVP
- create a component that lets the readers explore the newest features
- can be reused for future releases

![Page1](https://user-images.githubusercontent.com/47319502/162147565-fb3ea483-0d3a-4231-8482-046cca75d172.png)

see mockup [here](https://www.figma.com/file/FEyqRtZUk6tQazaNpvi7YL/Release-Features---What's-New?node-id=43%3A240)

**Comment by danieleguido** [comment]
done!
