### ISSUE TITLE
Replace numbering of articles per issue with publishing date

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#412]
![2022-04-12 11_19_18-Journal of Digital History](https://user-images.githubusercontent.com/47319502/162927391-836e1bbb-2f74-48cb-be58-26c963bf3306.png)

**Comment by biumiamy** [comment]
However, this would mean the date is the same for every article in this case.

For open issues it makes sense. For normal issues, we could instead imagine to write no numbers and adjust the date of the issue release: April 2022 (for example) 

![MacBook Pro 14_ - 1 (1)](https://user-images.githubusercontent.com/47319502/162929197-62649459-5734-4861-be63-cfe8b4456ab6.png)

**Comment by eliselavy** [comment]
<img width="685" alt="Screenshot 2022-04-12 at 11 44 26" src="https://user-images.githubusercontent.com/35602279/162931679-cd3399cb-a8bd-4711-90f9-786c32826284.png">

**Comment by eliselavy** [comment]
Addition of the numbering of the issue - publication date 
need to have this made before https://github.com/C2DH/journal-of-digital-history-backend/issues/107

**Comment by eliselavy** [comment]
jdh002 will be vol2. No 1

(2)1 - Published: 21 April 2022

**Comment by danieleguido** [comment]
Added order by (date asc, date desc, issue) in PR [fix/issue-412](https://github.com/C2DH/journal-of-digital-history/pull/492)


<img width="500" alt="Screenshot 2022-12-01 at 21 48 08" src="https://user-images.githubusercontent.com/1181642/205156348-9fa1c045-7075-4117-884b-7e2bd77bc7d5.png">
