### ISSUE TITLE
Change in the editorial 's board: for Stefano DALL'AGLIO + addition of Silke Schwandt

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#429]
I take the opportunity of this message to ask you if it's possible to update my profile on the website and change from "Assistant Professor" to "Associate Professor".

**Comment by eliselavy** [comment]
@inactinique information about text to provide for Silke Schwandt

**Comment by inactinique** [comment]
here is the information:
Silke Schwandt is Professor for Digital History in the Department for History, Philosophy and Theology at Bielefeld University.
And this is the link you can use: https://digital-history.uni-bielefeld.de/silke-schwandt/

@eliselavy

**Comment by eliselavy** [comment]
deploy in version v3.2.8
