### ISSUE TITLE
Allow trust notebook - javascript activated for jdh-observer github repository

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#440]
Allow trust notebook - javascript activated for jdh-observer github repository

**/proxy-githubusercontent/jdh-observer**/jdh002-VeaK58WBs82C/main/article-notebook.ipynb

**Comment by danieleguido** [comment]
In .env file I've added a comma separated lists of proxy prefix (all C2DH and all jdh-observer should be covered. To be tested:
``` 
REACT_APP_ALWAYS_JS_FROM_URL_PATH_PREFIX=/proxy-githubusercontent/C2DH/,/proxy-githubusercontent/jdh-observer/
```
