### ISSUE TITLE
User have the pdf 's view by looking at the following article https://journalofdigitalhistory.org/en/article/4yxHGiqXYRbX

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#448]
Raised by Florian  (Munich) and Bendix (Bremen), when they visit the url https://journalofdigitalhistory.org/en/article/4yxHGiqXYRbX
not the interactive version

Windows 11, Firefox 100.0.1 (64-Bit)
Also on Chrome  Version 101.0.4951.67 (Offizieller Build) (64-Bit)
Also with incognito
<img width="715" alt="image" src="https://user-images.githubusercontent.com/35602279/169511060-ad582598-1a2d-45f4-a580-f901deb4ad51.png">

**Comment by eliselavy** [comment]
clean the cache on the NGINX server

**Comment by eliselavy** [comment]
For next time need to look at the User-agent of the Request Headers
<img width="1141" alt="Screenshot 2022-05-20 at 15 21 10" src="https://user-images.githubusercontent.com/35602279/169536898-61b33b7a-0599-471e-b458-d7dea2ef3b0f.png">

**Comment by danieleguido** [comment]
It's not possible to reproduce the bug consistently, it is probably do to uni cache?
