### ISSUE TITLE
Become a reviewer button

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#457]
As it made for the journal of open humanities data: 
![Screenshot 2022-07-14 at 12 27 37](https://user-images.githubusercontent.com/35602279/178962445-138f3402-9216-4cc0-8531-091f3b8ed2c2.png)

https://openhumanitiesdata.metajnl.com/author/register/reviewer/

@inactinique to define the fields for the  form

**Comment by eliselavy** [comment]
Survey here: https://www.surveymonkey.com/r/CG35VJZ
Documentation here: 

[become a reviewer.pdf](https://github.com/C2DH/journal-of-digital-history/files/10706791/become.a.reviewer.pdf)

**Comment by eliselavy** [comment]
TO DO: 
implement a button “Become a reviewer” on the JDH website
-     Link to the button to the survey: 
https://www.surveymonkey.com/r/CG35VJZ

**Comment by eliselavy** [comment]
validation made by @inactinique 
where to put it ? design? @biumiamy

**Comment by biumiamy** [comment]
add it as a banner: https://github.com/C2DH/journal-of-digital-history/wiki/News

**Comment by inactinique** [comment]
Not happy with the text, but have to think about it.

**Comment by biumiamy** [comment]
some bg info on the process: 
- we don't have a specific pool of people, the managing editor reaches out the people he thinks would be a good match
- every potential author could become a reviewer (perhaps ask them after final publication if they would like to become a reviewer)
- possibility: give credit to the reviewer - show like the board on the website or show under the article

**Comment by biumiamy** [comment]
ask the board about giving credit or not?

**Comment by eliselavy** [comment]
In production 
![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/d0545d7d-4ff5-49a9-8155-1a68fe1c1364)
