### ISSUE TITLE
Add tech explanatory diagrams to Guideline

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#462]
visual style should match JDH overallstyle. Provide a SVG file to be styles (fonts, spacing etc)

**Comment by biumiamy** [comment]
last slide [here](https://docs.google.com/presentation/d/1pLmsEP5qU3rdXyXD9E3Hx6Ztqc1jTU3Mi2Mjj_zXlEg/edit#slide=id.g13dff3f1ea7_0_0)

![2022-07-26 14_16_12-Window](https://user-images.githubusercontent.com/47319502/181003747-1b8b3077-527d-412a-8d76-3dbc7bbb0596.png)

**Comment by biumiamy** [comment]
![how_to_create_an_article](https://user-images.githubusercontent.com/47319502/183365374-e4c9155f-622d-4e62-a5b5-a0608d9e775c.png)

**Comment by biumiamy** [comment]
updated version for better readability
![how_to_create_an_articel_overview_big3](https://user-images.githubusercontent.com/47319502/183589906-230aeef1-8449-42c3-97bf-093d0fa150c8.png)
