### ISSUE TITLE
Reduce size of jupyter notebook streamed from our proxy

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#474]
In jupyter notebooks, images a re stored as base64 strings. The bigger they are in size, the heavier they are. As many images are already stored on github, one quick solution would be to remove the cell output of each cell containing a remote loaded image.
This should be done in a proxy - so that we can safely cache the result in our local nginx. Images can then be lazy loaded (If we keep the info about the image width and height in px the lazy loading would be even better looking)

**Comment by eliselavy** [comment]
Need to look at this also https://github.com/arve0/ipynbcompress
