### ISSUE TITLE
add on the abstract submission page the possibility to select a cfp

### ISSUE THREAD

**Issue by inactinique** [C2DH/journal-of-digital-history#475]
For now, when authors are submitting an abstract, the abstrct will be linked to a specific cfp only if the authors pushed the 'submit abstract' button on the cfp page. If an author go directly to the abstract submission page, there’s no way to select a cfp.

We should give the possibility to authors to select a cfp even on the abstract submission page even if they don’t come from a cfp page. In this case, if they come from an abstract submission page, then this page's cfp would be preselected.

**Comment by eliselavy** [comment]
linked to https://github.com/C2DH/journal-of-digital-history-backend/issues/155

**Comment by eliselavy** [comment]
@danieleguido  in develop http://10.240.4.179/api/callofpaper/ return open cfp - folder_name need to be send to backend
