### ISSUE TITLE
Table of Contents is often hidden (too many figures or headings)

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#483]

**Comment by lwieneke** [comment]
Might be a related issue or another one: I can't scroll the ToC using Safari 16.0 on OS X 12.6

**Comment by biumiamy** [comment]
maybe sth like this?

![ToC_collapsing](https://user-images.githubusercontent.com/47319502/198055232-9b1e64e6-fbe1-44e0-aa37-028ea71fc338.png)

**Comment by danieleguido** [comment]
I think it's a very good idea @biumiamy !

**Comment by danieleguido** [comment]
Closing this issue, still pending connected issue: https://github.com/C2DH/journal-of-digital-history/issues/502

**Comment by eliselavy** [comment]
On this article http://10.240.4.179/en/article/hXsgcT9BZ5jP
Table of contents in JDH not reflect the one of the notebook

JDH table of contents:
![Screenshot 2023-01-03 at 10 52 51](https://user-images.githubusercontent.com/35602279/210334632-72d53823-aac7-4c73-84f9-7fe644c7ce41.png)


Jupyter notebook table of contents:

![Screenshot 2023-01-03 at 10 52 39](https://user-images.githubusercontent.com/35602279/210334726-d0846f70-670a-4dd6-9041-61d52f4b2e5a.png)

Missing:
 - Context and definitions / Data sources / Ethics
Missing introduction below Approach and Worflow

Notebook available here: https://github.com/jdh-observer/hXsgcT9BZ5jP/blob/main/article.ipynb

**Comment by eliselavy** [comment]
solved by HEADING cell centric

**Comment by danieleguido** [comment]
closing for now :)
