### ISSUE TITLE
add support fo magic javascript 

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#509]
See issue https://github.com/C2DH/journal-of-digital-history-jupyter-stack/issues/7 

The magic javascript is going to be deprecated it seems:
https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-javascript

There is a javascript extension, too, on **JupyterLab**:
https://www.npmjs.com/package/@jupyterlab/javascript-extension

**Comment by eliselavy** [comment]
In myBinder:
