### ISSUE TITLE
Images not displayed - output data image/png - R notebook

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#511]
Problem of images displayed related to R's notebook :

- with notebook tagged with aspect-ratio / w-Xpx / h-Xpx
![Screenshot 2023-01-25 at 13 48 57](https://user-images.githubusercontent.com/35602279/214569171-c61ebbc3-845a-4ffb-a6d3-79e85c278a88.png)

https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/skim-article.ipynb
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtOUhjZlRvaDdFWW04JTJGbWFpbiUyRnNraW0tYXJ0aWNsZS5pcHluYg==

=> the table of content is ok - but no figures displayed

- with notebook not tagged
https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/1_load_train_7075.ipynb
[
](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtOUhjZlRvaDdFWW04JTJGbWFpbiUyRjFfbG9hZF90cmFpbl83MDc1LmlweW5i?idx=82)

Other example here:

https://github.com/jdh-observer/jdh001-MyifnvNPDgUx/blob/main/taking-the-measure-of-social-democracy.ipynb

https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtTXlpZm52TlBEZ1V4JTJGbWFpbiUyRnRha2luZy10aGUtbWVhc3VyZS1vZi1zb2NpYWwtZGVtb2NyYWN5LmlweW5i?idx=75

**Comment by eliselavy** [comment]
R 's notebook - output data image/png and not data/image/jpeg

![Screenshot 2023-01-25 at 14 06 07](https://user-images.githubusercontent.com/35602279/214570985-12778b93-1989-4e59-917f-07ed640c4029.png)

**Comment by danieleguido** [comment]
The encoding was not right for the background-image css property, I've removed newlines in base64 encoding and it works. in principle this could be set from python code itself it seems, see https://stackoverflow.com/questions/30647219/remove-the-new-line-n-from-base64-encoded-strings-in-python3, they add `newline=false` No idea why R outputs newlines, but it will be fixed as soon as PR https://github.com/C2DH/journal-of-digital-history/pull/510 is merged.
<img width="469" alt="Screenshot 2023-01-25 at 16 56 46" src="https://user-images.githubusercontent.com/1181642/214611649-18c419ec-880a-4d5d-99af-99b06ff4dacf.png">
