### ISSUE TITLE
Split guideline notebooks in many notebooks

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#523]
Refine the layout of the Guideline page (design)

**Comment by biumiamy** [comment]
split current guideline into 3 sections:
- installation setup & all tools (split per OS)
- docker stack, reopen
- guideline styling

**Comment by biumiamy** [comment]
Show guideline page with tags as filter for content

![Guideline_1](https://user-images.githubusercontent.com/47319502/225568534-d17ecb0d-ff3d-473b-8fbb-1ab6f256066e.png)

**Comment by biumiamy** [comment]
Show ToC as soon as filtered and start with Guideline underneath

![Guideline_2](https://user-images.githubusercontent.com/47319502/225568685-84a8dc59-5946-4978-b3ab-51bab095df0a.png)

**Comment by biumiamy** [comment]
Tags as filters or radio buttons?
Solution for #407 with title shown above ToC as soon as the user scrolls away from header section

![Guideline_3](https://user-images.githubusercontent.com/47319502/225569048-304a6e8e-849f-4901-8a9a-ea00c86cc9fc.png)

**Comment by biumiamy** [comment]
https://github.com/C2DH/journal-of-digital-history/wiki/Guidelines

**Comment by biumiamy** [comment]
- use - instead of _
- and lower case

**Comment by biumiamy** [comment]
introduction notebook
general explanation of the workflow + image

**Comment by biumiamy** [comment]
- renamed the notebooks
- updated the introduction notebook
- updated the skim action (reference to the intro notebook) and ran it (but didnt correct the whitespace around the image..)
