### ISSUE TITLE
Update the description of Nadezhda Povroznik on the home page

### ISSUE THREAD

**Issue by inactinique** [C2DH/journal-of-digital-history#53]
Replace "Nadezhda Povroznik is Associate Professor at the Perm State University." by "[Nadezhda Povroznik](http://povroznik.com/eng/) is Associate Professor at the Department of the Interdisciplinary Historical Research and a Head of the Center for Digital Humanities at Perm State University."

**Comment by eliselavy** [comment]
deploy in production v1.0.6
