### ISSUE TITLE
Register JDH with chronoshub as an OA journal accepted by funding agencies

### ISSUE THREAD

**Issue by lwieneke** [C2DH/journal-of-digital-history#530]
We should highlight on the homepage that we are a [diamond](https://en.wikipedia.org/wiki/Diamond_open_access) OA journal and provide the ISSN of the journal as well. Currently it is only on the deGruyter site.

![2023-02-17_09-55-28](https://user-images.githubusercontent.com/1942767/219599556-1acbef42-4f91-44d6-9318-04b70feedf46.jpg)

**Comment by eliselavy** [comment]
@inactinique Florian mentionned this to the meeting of 27 october

**Comment by eliselavy** [comment]
On the DG website:

**Instant Gold OA without author APCs:** All authors retain copyright, unless – due to their local circumstances – their work is not copyrighted. Articles are published under the Creative Commons license CC-BY-NC-ND (authors can opt for CC-BY).

**Comment by inactinique** [comment]
Just registered the JDH with DOAJ. But can't see the chronoshub thing: on their website, there's nothing about registering a journal or?

**Comment by inactinique** [comment]
> Just registered the JDH with DOAJ. But can't see the chronoshub thing: on their website, there's nothing about registering a journal or?

poke @lwieneke

**Comment by eliselavy** [comment]
Too early for the moment to be registered in DOAJ
