### ISSUE TITLE
Tagging figure not clear for the authors

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#537]
During the technical review , really often now mistakes in the tagging figures ,see example below

![Screenshot 2023-03-31 at 11 43 22](https://user-images.githubusercontent.com/35602279/229091367-9557f6cb-ef19-457b-80de-cf8582272163.png)

or here 
<img width="438" alt="Screenshot 2023-03-30 at 18 16 19" src="https://user-images.githubusercontent.com/35602279/229091447-965f1f86-a38a-4d85-bae6-038121c9a1a1.png">

**Comment by eliselavy** [comment]
again another example see https://github.com/C2DH/jdh-notebook/issues/112
<img width="376" alt="Screenshot 2023-04-06 at 14 37 06" src="https://user-images.githubusercontent.com/35602279/230380768-3f0fc922-a01e-4184-850f-7dad9e5f57b2.png">
<img width="503" alt="Screenshot 2023-04-06 at 14 35 46" src="https://user-images.githubusercontent.com/35602279/230380789-2bf9b8f5-811f-429a-bf3e-179c68affee5.png">

**Comment by danieleguido** [comment]
Hi, 
it seems that the tagging of figure we had before was simpler in the end :) to be discussed...

**Comment by eliselavy** [comment]
- Rephrase in guidelines with example
- Example to add in the template repository https://github.com/C2DH/template_repo_JDH_R / https://github.com/C2DH/template_repo_JDH

**Comment by biumiamy** [comment]
I added this section to the guideline to explain the figure naming:

![figure-explanation](https://user-images.githubusercontent.com/47319502/231967710-fef821e0-0978-4897-a742-fbf9e343babb.png)

Do you think it is more clear now? @eliselavy @danieleguido ?

**Comment by eliselavy** [comment]
@biumiamy  yes really clear in term of tagging, but maybe also insist that the same logic applies for tables , tag table-....

Maybe also a point of tagging is important so that items are reflected in the table of contents.

About the label, there is a mix in your example between metadata inserted at the level of the cell, and metadata pass in parameter in the display method. if markdown table for example , need to be inserted at the metadata cell level.
Sometimes they are not aware where to find this metadata (see comment i made to author here https://github.com/C2DH/jdh-notebook/issues/105#issuecomment-1479717804)

Maybe a overview of the two methods.

**Comment by eliselavy** [comment]
@biumiamy you need to run the action https://github.com/C2DH/jdh-notebook/actions/workflows/github-actions-publishing.yml after having updating the guidelines notebook in order to have the version in production with the good size of the images

**Comment by biumiamy** [comment]
@eliselavy 
Should I always do the action after each commit? or after a I did a few corrections in a bundle? Probably each time I finished for the day. Perhaps that's the best. 

About the ToC: do you mean on the frontend (with a name like "figure 1: blabla-name")? or in the Juypter Notebook ToC to see it while one writes?

About the metadata - are you refering to the part at the top? or the example images below? And what's the best way to display it then instead of how it is currently? 

many questions :)

**Comment by eliselavy** [comment]
@biumiamy 
- the ToC in the frontend - in the jupyter notebook the Toc is only generated with the markdown 
- the metadata, yes i speak about the part here you put
![Screenshot 2023-04-19 at 13 51 11](https://user-images.githubusercontent.com/35602279/233066259-9ec10769-2c4a-485a-9c1b-9faea9579e16.png)
You need  to specify for the author where to find the metadata cell 
![Screenshot 2023-04-19 at 13 50 02](https://user-images.githubusercontent.com/35602279/233066029-4e9af6b2-c743-4931-bf4c-c90d2a90ee78.png)

- about the publishing action , indeed each time you want to release the guidelines on master you need to run it as the guidelines is loaded from here: 
`REACT_APP_NOTEBOOK_GUIDELINES_URL=https://journalofdigitalhistory.org/proxy-githubusercontent/C2DH/jdh-notebook/master/examples/Author_Guideline/skim-AuthorGuideline.ip`

**Comment by biumiamy** [comment]
updated the [skim action](https://github.com/C2DH/jdh-notebook/blob/master/.github/workflows/prepare-guideline-notebooks.yml) to work for all Guideline notebooks
