### ISSUE TITLE
Add github repo download to reproduce the code

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#546]
Mybinder is not 100% reliable as an external service and reviewer could be able to clone the original repo to get the code.

**Comment by eliselavy** [comment]
Button need to point on the github repo, in the article model repository_url
Ex: https://journalofdigitalhistory.org/api/articles/VeaK58WBs82C/. `repository_url`

**Comment by eliselavy** [comment]
In prod v4.1.5
