### ISSUE TITLE
Add breadcrumb for all articles

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#551]

**Comment by biumiamy** [comment]
Have everything in one spot and link to different notebooks:
https://github.com/C2DH/journal-of-digital-history/wiki/Guidelines 



add name of notebook like tags: 
![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/16b4d770-8ba4-478c-a61a-41b65e9d6fdb)

- need to add explanation how to maintain

**Comment by biumiamy** [comment]
Proposal to change layer switch to on/off button type of mechanic 

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/0ccbe1cf-9a15-4cdd-a9ec-695f14180ee0)

..and update button for Github (see before below)

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/6750aff5-d15a-40ce-99fd-ac2159a102e6)

**Comment by biumiamy** [comment]
or simplify it even more



![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/98a8985e-e695-4ae2-bd57-126c825f3b38)

**Comment by inactinique** [comment]
I would not simplify too much: shoudl be explicitly written hermeneutics / narrative, so I'm for your (very elegant) first solution.

**Comment by biumiamy** [comment]
Implemented.
