### ISSUE TITLE
integrate react-thebe for testing purposes only

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#552]
Thebe moved to React, so it's time to actually play with it! https://github.com/executablebooks/thebe/blob/0a62e506afa5f966ee6e4b33dbaa6c424516a8d1/apps/demo-react/src/WidgetsPage.tsx#L8

Thebe however expects a jupyterhub or jupyterlite kernel available somewhere.

**Comment by danieleguido** [comment]
see issue https://github.com/C2DH/journal-of-digital-history/issues/280
React-thebe is still 0.x library, so this would be just a test to check the future integration of Thebe ecosystem

**Comment by eliselavy** [comment]
Test the branch

**Comment by eliselavy** [comment]
To test pass in parameter the version of the parser: http://localhost:3001/en/article/m5GhKrrErgfE?**v=3**

Start a jupyterLab locally
