### ISSUE TITLE
Add loader for the guidelines between the different sub-item / first time need to reclick in order to have it

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#561]
The first time

There is a loader - but introduction is empty , need to click on other item of the menu (for example: preview article) and come back in order to have it:

<img width="1258" alt="Screenshot 2023-06-28 at 14 25 35" src="https://github.com/C2DH/journal-of-digital-history/assets/35602279/5b662d48-a45e-447a-be5a-7d214ad9c1e3">

Some strange situation between the sub-item

Windows button and still Mac page
<img width="991" alt="Screenshot 2023-06-28 at 14 11 54" src="https://github.com/C2DH/journal-of-digital-history/assets/35602279/eb2fb7b5-b6cd-4830-8ef0-c565e30771e0">

**Comment by danieleguido** [comment]
@eliselavy I've noticed it as well, it looks like a weird cache problem

**Comment by eliselavy** [comment]
In production v4.2.0 yesterday
