### ISSUE TITLE
hide issue titles when filtering and no article is in an issue

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#562]
when filtering, we should hide the issue titles that have no articles matching the selected filter?

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/eb0ca2b6-14ad-4e4c-821b-2b48e47dc025)

**Comment by danieleguido** [comment]
Done, current solution: ![Screenshot 2024-03-28 at 14 51 01](https://github.com/C2DH/journal-of-digital-history/assets/1181642/4486679e-a3a8-41bc-9fa3-ec5f6679be3d)
