### ISSUE TITLE
dialog tag

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#574]
For this article: 
Chronoreferencing the Italian-Slovenian Borderlands. Citizen Science, Digital Hermeneutics and Output Criticism
http://10.240.4.179/en/article/6ig87tC5GKjQ 

- currently the table formatting looks like this on the N- and H-layer (the colors are not aligned with H-layer color scheme)

![Image](https://user-images.githubusercontent.com/47319502/268986830-c29f851c-d811-4c02-83bd-fcff85b46f76.png)

![Image](https://user-images.githubusercontent.com/47319502/268985688-8d199391-d9eb-421f-8926-9c57a4ab6dfc.png)

desirable: 
- change color scheme to match H-layer
- align styling on N- and H-layer to look the same even in the preview

![Image](https://user-images.githubusercontent.com/47319502/269033298-f35b9c01-d3b0-4ea3-8832-328611c386a7.png)

or dialog style like a chat for comfortable reading:

![Image](https://user-images.githubusercontent.com/47319502/269000227-a473e6ee-2fdb-44a6-9fc8-4e72f512a056.png)

Is there sth like this we can do in the frontend?

And bonus question: could the text appear interactively to the audio file?

**Comment by biumiamy** [comment]
- add dialog tag

**Comment by biumiamy** [comment]
another issue: sometimes there are line breaks, but they are shown as a new line in the table.. need to find a solution for that (?)

**Comment by danieleguido** [comment]
You have to put explicit `<br />` and I suggest to add pipe character at the beginning of every new line

| A  |  B  |
| --- | --- | 
| Hello B!  | |
| | Hello A! ... <br /> How are you?  |
| Not bad!  <br /> What about you? | |

**Comment by eliselavy** [comment]
@danieleguido example here: https://github.com/C2DH/jdh-notebook/blob/master/examples/sound-dialog.ipynb

**Comment by biumiamy** [comment]
ready to test: https://latest--journalofdigitalhistory.netlify.app/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZDMkRIJTJGamRoLW5vdGVib29rJTJGbWFzdGVyJTJGZXhhbXBsZXMlMkZzb3VuZC1kaWFsb2cuaXB5bmI=?idx=1

**Comment by biumiamy** [comment]
and issue with audio file in the example notebook - need to fix: https://github.com/C2DH/jdh-notebook/blob/master/examples/sound-dialog.ipynb

**Comment by biumiamy** [comment]
Issue with sound resolved

**Comment by biumiamy** [comment]
Requested: Right align second speaker:

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/56d27dc4-3cea-49ca-97d3-7efc4ee6d60d)

**Comment by biumiamy** [comment]
I checked all tables [here](https://docs.google.com/spreadsheets/d/1ZLZkpu0lIss7dkohf_z0oVdQ-jjzi8xQiBciN8h9EVE/edit?usp=sharing)
