### ISSUE TITLE
advanced table

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#575]
user need from [Chronoreferencing the Italian-Slovenian Borderlands](http://10.240.4.179/en/article/6ig87tC5GKjQ)
- link from text (comment or post) to line in a table

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/9bae15ca-0b1a-442f-a84b-1e506a94eb68)

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/711d3fc2-47aa-46dc-8169-a0029c8b093d)

with line in focus so the reader doesn't need to search

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/63e0d9f3-1c53-488f-8231-68c5fee1e7dd)

two options for example:
- show popover with small table section
- jump to table with line in focus (and back to reading button)
- (offer sorting column functionality)

**Comment by biumiamy** [comment]
https://tanstack.com/table/v8/docs/examples/react/basic

**Comment by danieleguido** [comment]
I suggest to add a `datatable-` tag to the table, so that I can add this component on top of the data https://tanstack.com/table/v8/docs/examples/react/basic

**Comment by biumiamy** [comment]
here's a example notebook with the table and references to it: https://github.com/C2DH/jdh-notebook/blob/master/examples/advanced_table.ipynb

**Comment by eliselavy** [comment]
Maybe in the TOC should be referenced also as table @biumiamy @danieleguido 

![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/6a71e3f2-22c1-428f-b29a-e2db2176be55)

**Comment by eliselavy** [comment]
@danieleguido example added in the  https://github.com/C2DH/jdh-notebook/blob/master/examples/advanced_table.ipynb related to https://github.com/C2DH/jdh-notebook/issues/135#issuecomment-1863099654

**Comment by eliselavy** [comment]
Example coming from here: https://github.com/jdh-observer/4ZDXFXQwhoA8/blob/bdb87b8826c436907817b4fc9e5f172288496c95/delors_anonymised.ipynb

Problem display with the TOC - how to use it without retagging everything

![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/1a35973f-730d-4b46-a0c5-253444c73657)

For me problem of use, if this tag is assigned later in the publication process, for example design review, need to retag all.
This data-table-* is more a designed tag for me.

![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/bf35c74f-4a91-4204-b012-e6a9baa2845f)

**Comment by danieleguido** [comment]
Hi @eliselavy a solution to this problem could be:
- we tag all tables with the usual `table-` tag
- we add just a new `data-table` tag
This way we can toggle the datatable feature without changing the ref to tables in the text of the article. Could this solve your issue?

**Comment by danieleguido** [comment]
I've just merged in `develop`, finally the fact of adding the `data-table` tag hasn't any impact on the existing rules. Soon on develop :). I suggest to close this huge issue as the feature is out there. We can always create new issues if necessary.

**Comment by eliselavy** [comment]
By using this:


![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/3e26988b-b272-41da-be8f-ec47e7ad7782)

table appears two times

![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/52d47a13-537e-4682-9a9b-64f4f698fd2c)

**Comment by eliselavy** [comment]
> if you want to paginate with 20 lines, simply add the tag **page-size-20**, or for 3 lines **page-size-3**

**Comment by danieleguido** [comment]
Duplication of table fixed in the previous commit

**Comment by eliselavy** [comment]
Available in production : https://github.com/C2DH/journal-of-digital-history/releases/tag/v4.4.1

**Comment by biumiamy** [comment]
added it to the guideline as well:

<img width="850" alt="2024-02-02 10_29_26-Journal of Digital History" src="https://github.com/C2DH/journal-of-digital-history/assets/47319502/bb43194c-2a48-4c8c-9757-1d65c7b39192">
