### ISSUE TITLE
update ToC

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#578]
- current ToC doesnt show the headlines per chapter very well (example [here](http://10.240.4.179/en/article/hXsgcT9BZ5jP))

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/fb70bf27-cecb-46c5-b439-ca2b39b47c68)

- need to expand manually to see.. even when scrolled past it already

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/f76f08f5-987a-4369-8877-042755bb94b3)

- example of [JOVI article](https://www.journalovi.org/2023-park-gatherplots/#intro) shows headlines and then expands sub headlines gradually

![Image](https://github.com/C2DH/journal-of-digital-history/assets/47319502/46cb6714-d074-4425-846a-8ae0784812bd)

**Comment by biumiamy** [comment]
- add audio
- video
- ...
-

**Comment by biumiamy** [comment]
here is a fragment: https://github.com/C2DH/jdh-notebook/blob/master/examples/sound-dialog.ipynb

**Comment by biumiamy** [comment]
still missing: color-coding for hermeneutics layer

**Comment by biumiamy** [comment]
@danieleguido
When scrolling, currently not visible where the scrolling position is - should show current position in _bold_

**Comment by eliselavy** [comment]
@danieleguido scrolling need to be added - can not use  the guidelines

![Image](https://github.com/C2DH/journal-of-digital-history/assets/35602279/db5e2f53-897e-4d66-ae29-7e8ba4378ad7)

**Comment by eliselavy** [comment]
Available in production https://github.com/C2DH/journal-of-digital-history/releases/tag/v4.4.1
