### ISSUE TITLE
Integrate Bluesky url @jdighist.bsky.social / Define the use

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#579]
- Integrate Bluesky url @jdighist.bsky.social
- Look at the  metadata to define

- Define use of Twitter / Bluesky @inactinique

**Comment by inactinique** [comment]
Define use of Twitter / Bluesky.

We publish one (or two) last tweet(s):

> The evolution of X (formerly Twitter) over the last year or so has turned it into a platform that we feel is no longer compatible with the values of higher education and research, values that the Journal of Digital History wishes to promote.

> As a result, while this account will remain open in order to preserve access for our readers to what we have already published, we will henceforth be talking about our activities on Bluesky. We are of course still on Facebook.


We then stop publishing on X and start publishing on Bluesky (and we stay on Facebook).

**Comment by biumiamy** [comment]
It looks very strange that we still have Twitter but we're not using it anymore ;)

So.. I sent two PRs to change the icon and the text & link from Twitter to Bluesky
https://github.com/C2DH/journal-of-digital-history/pull/669 
https://github.com/C2DH/journal-of-digital-history/pull/668

**Comment by eliselavy** [comment]
in prod @biumiamy v5.0.2
