### ISSUE TITLE
Add Ethics Reviewer page and add reviewer info on About page

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#602]

**Comment by inactinique** [comment]
And here is the text to be added on the About page for the part about the reviewers:

"Running an academic journal of the highest scientific standards would be impossible without the critical work of benevolent reviewers. Reviewers play an essential role, but unfortunately are often invisible in the academic quality control. Seeing the complex nature of our review process (reviewers have to evaluate both the content and the underlaying data/software environment), we would express our deepest gratitude to our reviewers who, alongside authors and our team, make the Journal of Digital History a vibrant hub for data-driven scholarship in the field of digital history."

**Comment by danieleguido** [comment]
It is already integrated on our wiki: https://journalofdigitalhistory.org/en/review-policy

**Comment by inactinique** [comment]
@danieleguido The ethics declaration do not display (just the title appears). Is that normal?

I have modified the announcement about the switch to single blind peer review: https://github.com/C2DH/journal-of-digital-history/wiki/The-Journal-of-Digital-History-switches-to-single%E2%80%90blind-peer-review

**Comment by danieleguido** [comment]
Closing this issue as it has been solved already :) 
The declaration is here https://journalofdigitalhistory.org/en/review-policy
