### ISSUE TITLE
Problem with anchor:  link properly displayed but  doesn't work correctly - link rendered as figure-undefined but anchor work

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#639]
First case: The anchor linked is properly rendered but doesn't work.

In a new article:

http://10.240.4.179/en/article/jYcpqGfdXPra?idx=35

Timeline define as an anchor 
![Screenshot 2024-05-30 at 16 12 12](https://github.com/C2DH/journal-of-digital-history/assets/35602279/fc0674a0-0a54-4df7-919a-43535bf89d0d)

See here in the raw:

https://raw.githubusercontent.com/jdh-observer/jYcpqGfdXPra/main/article.ipynb

` "To chart the religious practises of a varied population - laypeople and religious professionals alike - in letter writing, we made use of the Parsed Corpus of Early English Correspondence, commonly abbreviated as PCEEC (<cite data-cite=\"9104992/IDVB5BT9\"></cite>). This 2.2 million word corpus consists of 4970 personal letters, drawn from the edited publications of 84 different correspondences that took place between ca. 1410 and 1695. **For a visual overview, we refer to our [timeline](#anchor-figure-timeline).** Even though the wide-spread illiteracy at the time of writing restricts the corpus to the upper echelons of society, care has been taken to draw from as broad a pool of letter writers as possible. Nearly a fifth of the writers, for example, were women, and much effort has been spent on the collection and correction of the corpus' metadata, including biographical information on all letter writers and addressees. f\n",
`

```
},
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "tags": [
     "figure-timeline-*",
     "anchor-figure-timeline"
    ]
   },
   "outputs": [
    {
     "data": {
```

In old article: https://journalofdigitalhistory.org/en/article/4yxHGiqXYRbX?idx=29

Second case: the anchor linked is not correctly displayed, cf **figure undefined** but the internal link works

See here:

![Screenshot 2024-05-30 at 16 15 21](https://github.com/C2DH/journal-of-digital-history/assets/35602279/fa3b246a-683f-472a-b093-b30283c93cda)

In the raw: 

```
 "source": [
    "This section explores the distribution of divine appeals in our letters throughout the entire early modern period. First ([4.1](#anchor-divine-appeals)), their dispersion through the letters is charted. Did the relative number of divine appeals increase or decrease as time progressed? Were they more common in the rather formulaic opening and closing statements of the letters? Second ([4.2](#anchor-communities)), we look at the social distribution of the appeals. Does every correspondence in the corpus yield the same (relative) number of divine appeals, or do some correspondents employ them more than others? If that is the case, what is their social profile?"
   ]
  },
```
https://raw.githubusercontent.com/jdh-observer/jYcpqGfdXPra/main/article.ipynb

```
  "cell_type": "markdown",
   "metadata": {
    "tags": [
     "anchor-divine-appeals"
    ]
   },
   "source": [
    "###  Divine appeals in letter opening, body and closing statements"
   ]
  },
```

Other example here:

![Screenshot 2024-05-30 at 16 03 56](https://github.com/C2DH/journal-of-digital-history/assets/35602279/d20f865b-c3f8-42ad-b55d-f0bce1a3e7cd)

https://journalofdigitalhistory.org/en/article/WBqfZzfi7nHK

In the raw: https://raw.githubusercontent.com/jdh-observer/jdh001-WBqfZzfi7nHK/main/scripts/skim-article.ipynb

`account for uncertainty, which is a more entailed process than streamlining the spelling of vocabularies in a list of standardized descriptors. Concepts and meanings need to be mapped and related among datasets to make meaningful analysis possible, either manually or with the application of machine learning (<cite data-cite=\"7109337/E3C4WXXH\"></cite>). Computer-assisted analysis (e.g. distant reading) of fragmented texts hinges on the reconciliation of alterations to the Leiden editorial standard, see ([Step 2.3 in Hermeneutics](#anchor-hermeneutics-2-3)). Furthermore, researchers need to develop their tools and pipelines to tackle the idiosyncrasies of epigraphic monuments as standard Natural Language Processing pipelines trained on literary data do not work the same way on the texts of inscriptions. "`

**Comment by danieleguido** [comment]
It seems that for some reason the anchor tag cannot be found, probably because it is already indicated as "figure". 
![Screenshot 2024-06-04 at 10 28 58](https://github.com/C2DH/journal-of-digital-history/assets/1181642/bafacbbd-0e7c-488d-b599-9e93750cf0a9)

**Comment by danieleguido** [comment]
```
"source": [
    "This section explores the distribution of divine appeals in our letters throughout the entire early modern period. First ([4.1](#anchor-divine-appeals)), their dispersion through the letters is charted. Did the relative number of divine appeals increase or decrease as time progressed? Were they more common in the rather formulaic opening and closing statements of the letters? Second ([4.2](#anchor-communities)), we ..."
```

**Comment by eliselavy** [comment]
In prod v4.6.0
