### ISSUE TITLE
V3 : images should fit view port

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#653]
Here:

<img width="1425" alt="Screenshot 2024-08-01 at 11 26 28" src="https://github.com/user-attachments/assets/fc695c9e-7a78-49ad-8d49-41a48ece85da">

**Comment by danieleguido** [comment]
from @frederic-reis 
- The height tag determines the height of the picture (do not apply for cover)
- If the picture width exceeds the container width or if the height tag is not defined, the aspect-ratio determine the height of the picture, the width is 100% of the container
- If the aspect-ratio tag is not defined, the height of the picture is defined on 0.5 of the height of the window (0.8 for cover)

**Comment by eliselavy** [comment]
Ok fixed
<img width="1226" alt="Screenshot 2024-08-01 at 11 24 20" src="https://github.com/user-attachments/assets/b7e930e4-a043-476a-8ef2-18bd2030677f">
