### ISSUE TITLE
V3: fix click on Bibliography from ToC, fix click on paragraph number

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#655]

**Comment by eliselavy** [comment]
Maybe as now we used for data&code the black background, another colour should be used for the reference
![Screenshot 2024-08-01 at 14 57 04](https://github.com/user-attachments/assets/63f41a6e-95d6-4b76-8ed8-aa54fc4a3af5)

**Comment by frederic-reis** [comment]
The click on paragraph number should be fixed

**Comment by eliselavy** [comment]
> The click on paragraph number should be fixed

yes @frederic-reis but no bibliography in V3

**Comment by eliselavy** [comment]
> > The click on paragraph number should be fixed
> 
> yes @frederic-reis but no bibliography in V3 in the article view ( in preview yes)

Ok forget about it link to the fact can not scroll in the TOC in the article view , link to: https://github.com/C2DH/journal-of-digital-history/issues/671

**Comment by eliselavy** [comment]
@frederic-reis the bibliography is not clickable
