### ISSUE TITLE
V3: dialog table is not displayed correctly

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history#658]

**Comment by biumiamy** [comment]
For example here: https://journalofdigitalhistory.netlify.app/en/article/6ig87tC5GKjQ?idx=59&v=3

![2024-10-07 09_50_38-Journal of Digital History](https://github.com/user-attachments/assets/8348d6b3-bf2d-496f-acc7-0c1c067bc254)

**Comment by frederic-reis** [comment]
I put the dialog back on V3 and I set the code for Sound on read-only mode without tools
