### ISSUE TITLE
Adaptation to enable article displayed in V3

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#660]
Prepare version where last version of V3 is enabled

Some article will be published in V2 , some in V3
Still use the v=3 parameter in the url 

Need to merge the branch: https://github.com/C2DH/journal-of-digital-history/pull/637

But need to integrate the Flask api: https://github.com/C2DH/journal-of-digital-history-code-explainer

see here : https://github.com/C2DH/journal-digital-history-docker-stack/issues/23

**Comment by eliselavy** [comment]
To display article we pass the notebook url , it means all the all the caracters after the url : https://journalofdigitalhistory.org/en/notebook-viewer/ but the ?v=3 need to pass 

required some adaptation in the code

**Comment by danieleguido** [comment]
Hi @eliselavy, better to pass an explicit parameter, hence `parserVersion` is fine. We don't need the array, so I'd expect smth like:

```json
   "data": {
        "title": [
            "# Chronoferencing the Italian-Slovenian Borderlands. Citizen Science, Oral History and Output Criticism\n"
        ],
        "parserVersion": "3"
    }
```

**Comment by eliselavy** [comment]
> Hi @eliselavy, better to pass an explicit parameter, hence `parserVersion` is fine. We don't need the array, so I'd expect smth like:
> 
> ```json
>    "data": {
>         "title": [
>             "# Chronoferencing the Italian-Slovenian Borderlands. Citizen Science, Oral History and Output Criticism\n"
>         ],
>         "parserVersion": "3"
>     }
> ```

ok @danieleguido the example has been updated, i put array has all the property in the data field were array...

**Comment by eliselavy** [comment]
What about the citation: we will register as a secondary url for crossref for the citation the url with ?v=3

**Comment by danieleguido** [comment]
There's no need to add v3 as parameter, it will be handled internally by the component

**Comment by eliselavy** [comment]
Need to thing also to clarify how the Preview functionnality will be used as the URL is used for the peer-review and the final-author-check

**Comment by danieleguido** [comment]
the v=3 param in the URL  will always be available in the preview notebook

**Comment by frederic-reis** [comment]
The viewer version is determined by the following rules:
* The v query parameter (ex: v=3)
* If not defined, the `data.parserVersion` property defined in the article JSON file
* If not defined, the default version is 2

**Comment by eliselavy** [comment]
In prod @inactinique https://journalofdigitalhistory.org/en/article/6ig87tC5GKjQ
