### ISSUE TITLE
Display ISSN on the homepage

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#662]
ISSN for the journal: ISSN: 2747-5271
Available on the De Gruyter's website: https://www.degruyter.com/journal/key/jdh/html

> https://www.issn.org/understanding-the-issn/what-is-an-issn/
For a publication in electronic media, the ISSN should be shown:
on the homepage or on the main menu, if it is an online publication,

**Comment by biumiamy** [comment]
![2024-10-21-15_11_12-Journal-of-Digital-History_update](https://github.com/user-attachments/assets/ee19c114-b00f-4e71-b840-0363b1ee96ee)

**Comment by biumiamy** [comment]
PR:
https://github.com/C2DH/journal-of-digital-history/pull/664

**Comment by biumiamy** [comment]
and added it to the about page as well

![2024-10-21 16_09_02-Journal of Digital History](https://github.com/user-attachments/assets/8f5b8814-c146-457c-a97f-7ccac38e7d7c)

**Comment by eliselavy** [comment]
in prod
