### ISSUE TITLE
v3: no possibility to scroll the table of contents in the article view / ok in preview

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#671]
In v3 article 's view:
<img width="581" alt="Screenshot 2024-11-07 at 12 29 17" src="https://github.com/user-attachments/assets/13c62e19-8d01-4bf3-9078-22b24e04578f">

In v3 preview:
<img width="500" alt="Screenshot 2024-11-07 at 12 29 40" src="https://github.com/user-attachments/assets/56edf22a-ac05-4248-be3e-0c091ee8872b">

**Comment by eliselavy** [comment]
@frederic-reis in fact it really depends , here i am in the preview, the scrollbar  appeared , it uncollapse it a node, and after block 
<img width="919" alt="Screenshot 2024-11-07 at 18 24 16" src="https://github.com/user-attachments/assets/2fbb0060-efd7-44c0-a735-535dac0059f7">

**Comment by eliselavy** [comment]
@biumiamy i have problem to determine the scenari , also we have selected a paragraph , it means , an id in the url , how the TOC needs to react?

**Comment by danieleguido** [comment]
@eliselavy can you add a link to the article in v3? The scrolling should always be there if the page is too small.
