### ISSUE TITLE
Datatable  style when  scrollbar

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#672]
<img width="1407" alt="Screenshot 2024-11-07 at 14 00 02" src="https://github.com/user-attachments/assets/2e1bb27e-9d11-41ed-9f1e-3dff76c8f793">

the example here: 
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0OFJHdXpNNHFmVkElMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==?idx=46&layer=hermeneutics&lh=683&pidx=46&pl=narrative&y=85

<img width="1387" alt="Screenshot 2024-11-07 at 14 03 54" src="https://github.com/user-attachments/assets/eabfbb1f-06d8-40cd-8c74-c84b50aa6d59">

**Comment by frederic-reis** [comment]
It's fixed: https://journalofdigitalhistory.netlify.app/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0OFJHdXpNNHFmVkElMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==?idx=46&layer=hermeneutics&lh=683&pidx=46&pl=narrative&y=85
