### ISSUE TITLE
Investigate undefined in front and  escape html tag  in references the html tag <div class=“cite2c-biblio”></div>

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/journal-of-digital-history#74]
Investigate <cite data-cite=“undefined”></cite> and  escape html tag  in references the html tag <div class=“cite2c-biblio”></div>

Some undefined reference appears by loading following notebook:

- https://github.com/jdh-observer/jdh001-JJszM3GwAYDs/tree/main/namelesscrowd
- https://github.com/jdh-observer/jdh001-4yxHGiqXYRbX

<img width="925" alt="106Analysis The criterion of the sociological composition of the crowd seems to be the most decisive so far to" src="https://user-images.githubusercontent.com/81378245/118982287-906b5000-b97b-11eb-86b1-171ab33531b0.png">

but in the notebook it's defined

, that is crowd of plebeians, in Rome **(<cite data-cite="2272257/9D9AZDPV"></cite> p. 177),** or crowd of “common soldiers” (_gregarii milites_, Tac., _Hist._, 1.36.3, 1.46.4, 3.31.2), distinguished from the prefects and the legates (Tac., _Hist._, 2.70.5, 4.36–37, 4.57, _Ann._, 1.49.2), from the tribunes and the centurions

**Comment by eliselavy** [comment]
Need to define a stylesheet according to the type of :

webpage / article / article-magazine / book.....

**Comment by eliselavy** [comment]
type webpage take the container-title
if author[] > 1 add  *et al.*
if no year look at issued: { literal: "c. 1940s"}

**Comment by eliselavy** [comment]
escape html tag in references the html tag <div class=“cite2c-biblio”></div>. just by adding hidden tag in the jupyter notebook
