### ISSUE TITLE
Numbering of figures find solution 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#82]
numbering of figures , need to provide guidelines

author add in the jupyter : Figure 1.....

problem also figure generated with matplotlib...

Example here:

<img width="1103" alt="Screenshot 2021-05-28 at 12 59 28" src="https://user-images.githubusercontent.com/35602279/119985949-97b9db80-bfc3-11eb-89fa-2edf0f9c959a.png">

**Comment by eliselavy** [comment]
![Uploading Screenshot 2021-05-28 at 12.59.28.png…]()

**Comment by danieleguido** [comment]
I suggest to create a "fake" link in markdown so that we use a sort of identifier per each figure `[Fig](fig-word-cloud)` which will be linked to the metadata of the cell containing the figure... Basically what we do with cite2c.

**Comment by eliselavy** [comment]
Ok with the following notebook: https://github.com/jdh-observer/jdh001-JJszM3GwAYDs/blob/test/figure/namelesscrowd/The-Nameless-Crowd_anon_V3.ipynb

For this notebook: 
https://github.com/jdh-observer/jdh001-4yxHGiqXYRbX/blob/test/figure/TopicSpecificCorpusBuilding.ipynb

- do you need to implement a tag table  ? is it a practice to use Table 1 Table 2 

<img width="990" alt="Screenshot 2021-06-02 at 18 18 22" src="https://user-images.githubusercontent.com/35602279/120516998-413c0b00-c3d0-11eb-94a4-7808704df57a.png">

- in the case of two figures per cell?
