### ISSUE TITLE
Display multiple images in one figure (<IPython.core.display.Image object>)

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#84]
For image Not display <IPython.core.display.Image object>

**Comment by danieleguido** [comment]
?

**Comment by eliselavy** [comment]
<img width="874" alt="Screenshot 2021-05-31 at 13 19 44" src="https://user-images.githubusercontent.com/35602279/120185824-ff199a80-c212-11eb-9716-038447c64ee5.png">
here example of code block dispalyed

**Comment by eliselavy** [comment]
here not 
![Uploading Screenshot 2021-05-31 at 13.19.56.png…]()

**Comment by eliselavy** [comment]
need to provide metadata
display(Image("images/return_migration.png"), metadata=metadata)
metadata={
    "jdh":{
        "module": "object",
        "object": {
          "type": "image",
          "source": [
            "Figure 2: Salzburger Blatt, 5.5.1946, p. 8. copyright: Bibliothek nationale"
          ],
            
        }
    }
}
