### ISSUE TITLE
Some authors use pygal librairie and render in html  : need to be displayed

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#85]
http://www.pygal.org/en/stable/

dot_chart = pygal.Dot(dot_size=700, legend_box_size=6, x_label_rotation=70, style=DarkStyle, height=450,legend_at_bottom=True, legend_at_bottom_columns=4)

print('Figure 10: Dot chart of manual annotations on the sub-corpus (step 13)')
display(HTML(base_html.format(rendered_chart=dot_chart.render(is_unicode=True))))

<img width="1139" alt="Screenshot 2021-05-31 at 16 03 23" src="https://user-images.githubusercontent.com/35602279/120205007-bcaf8800-c229-11eb-89ed-665011cc22c9.png">

**Comment by eliselavy** [comment]
temporary fixed image has been provided

**Comment by danieleguido** [comment]
@eliselavy the PR https://github.com/C2DH/journal-of-digital-history/pull/95 should cover this scenario, too... to be tested ;)
