### ISSUE TITLE
8 tables designed by using display(df_article_1.style.set_caption.  are not displayed correctly in the preview 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#87]
8 tables designed by using display(df_article_1.style.set_caption.  are not displayed correctly in the preview for the following notebook https://github.com/jdh-observer/jdh001-4yxHGiqXYRbX

<img width="1041" alt="Screenshot 2021-06-01 at 12 36 53" src="https://user-images.githubusercontent.com/35602279/120309951-1d949a00-c2d6-11eb-8865-b9e1a04be918.png">

here the display in JDH:
<img width="1013" alt="Screenshot 2021-06-01 at 12 42 41" src="https://user-images.githubusercontent.com/35602279/120310616-dd81e700-c2d6-11eb-97f0-ca7d4807ccee.png">

**Comment by eliselavy** [comment]
Here are the JSON output:

 "outputs": [
    {
     "data": {
      "text/html": [
       "<style  type=\"text/css\" >\n",
       "</style><table id=\"T_c00ea840_c2ba_11eb_ac44_e470b8a9ba13\" ><caption>Table 2: Neure Freie Presse, March 1935 | left: original; right: translation</caption><thead>    <tr>        <th class=\"col_heading level0 col0\" >Original Text</th>        <th class=\"col_heading level0 col1\" >Translation</th>    </tr></thead><tbody>\n",
       "                <tr>\n",
       "                                <td id=\"T_c00ea840_c2ba_11eb_ac44_e470b8a9ba13row0_col0\" class=\"data row0 col0\" >London. von Auslandgeldern aus Londoner Dienst der „Neuen Freien Presse“. London, 4. März. „Times“ schreibt über die Sterlingverkäufe auf den ausländischen Märkten: Das neue Abgleiten des Pfundkurses, das nun auf die etwa 1Oprozentige Abwertung des Jahres 1934 folgt, ist hauptsächlich eine Folge der Rückwanderung der ansländischen Fonds, die in den Jahren 1932 bis 1933 in sehr hohen Beträgen nach London gesandt worden waren. Die Umkehrung dieser Bewegung hat verschiedene Ursachen. Zum Beispiel hat die Fixierung der Relation zwischen Gold= und Dollarpreis im vorigen Jahr eine beträchtliche Rückwanderung amerikansschen Geldes nach den Vereinigten Staaten mit sich gebracht. Ein weiterer Faktor, der zur Abschwächung des Pfundes beitrug, ist die niedrige Zinsrate in London im Verhältnis zu jeuer der Goldblockländer.</td>\n",
       "                        <td id=\"T_c00ea840_c2ba_11eb_ac44_e470b8a9ba13row0_col1\" class=\"data row0 col1\" >London. of foreign money from London service of the 'Neue Freie Presse'. London, March 4. 'Times' writes on sterling sales in foreign markets: The new slide in the rate of the pound, which now follows the depreciation of about 1O per cent. in 1934, is chiefly a consequence of the return of domestic funds which had been sent to London in very large sums in 1932 to 1933. The reversal of this movement has several causes. For example, the fixing of the relation between the price of gold and the price of the dollar last year brought about a considerable return of American money to the United States. Another factor contributing to the weakening of the pound is the low interest rate in London relative to that of any of the gold bloc countries.</td>\n",
       "            </tr>\n",
       "    </tbody></table>"
      ],
      "text/plain": [
       "<pandas.io.formats.style.Styler at 0x1ec3aa49bc8>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ]

**Comment by eliselavy** [comment]
- quick workaround: use picture
- look at to the documentation of https://markdown-it.github.io/markdown-it/ to include some html tags
In **logic/api/ipynb.js**
```
import MarkdownIt from 'markdown-it'
const markdownParser = MarkdownIt({
  html: false,
  linkify: true,
  typographer: true
})
```

**Comment by eliselavy** [comment]
@danieleguido example here https://github.com/C2DH/jdh-notebook/blob/master/examples/style-dataframe.ipynb

**Comment by biumiamy** [comment]
in T**opic-specific corpus building: The creation of a representative newspaper corpus on the topic of return migration using text mining methods**, it's all double. one time in cell manner, one time like a photo or whatever that is (see attachment)
![2021-06-07 10_23_23-Window](https://user-images.githubusercontent.com/47319502/120984520-04c73100-c77b-11eb-9d97-69fa97513a07.png)

**Comment by biumiamy** [comment]
in _Topic-specific corpus building: The creation of a representative newspaper corpus on the topic of return migration using text mining methods_, the table is now shown double. one time in cell manner, one time like a photo (or whatever that is?)

**Comment by biumiamy** [comment]
![2021-06-07 10_23_23-Window](https://user-images.githubusercontent.com/47319502/120988114-8a001500-c77e-11eb-8854-11fc738aed0c.png)
