### ISSUE TITLE
To use markdown in the print : display(Markdown(string)) doesn't work

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#89]
here notebook defining function not interpreted correctly 

<img width="934" alt="# définition d'une fonction pour utiliser du markdown dans les print" src="https://user-images.githubusercontent.com/35602279/120519183-a3960b00-c3d2-11eb-9e01-2f27c3e0a59b.png">

In the following notebook:
 https://github.com/jdh-observer/jdh001-JJszM3GwAYDs/blob/main/namelesscrowd/The-Nameless-Crowd_anon_V3.ipynb

**Comment by danieleguido** [comment]
@eliselavy can you create a tiny notebook on jdh-notebook with this method?
<img width="702" alt="Screenshot 2021-06-03 at 14 56 20" src="https://user-images.githubusercontent.com/1181642/120649054-a0575980-c47c-11eb-9a6d-5f355dd2a5c5.png">

**Comment by eliselavy** [comment]
@danieleguido example available here https://github.com/C2DH/jdh-notebook/blob/master/examples/print-markdown.ipynb
