### ISSUE TITLE
Update labelling to fit requirement, it means : figure and not Fig - table and not Table / ref tag

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#91]
Update labelling to fit requirement, it means : figure and not Fig - table and not Table

[figure 1](#figure-1)
[table 1](#table-1)

**Comment by danieleguido** [comment]
@eliselavy this issue should be moved to jdh-notebook

**Comment by eliselavy** [comment]
no @danieleguido it's in the frontend the dispaly come from 
<img width="844" alt="Screenshot 2021-06-04 at 16 31 23" src="https://user-images.githubusercontent.com/35602279/120817928-6bb5d180-c552-11eb-94d1-e92d7f3fdfe0.png">

**Comment by danieleguido** [comment]
Fixed as translation labels, but add the issue in the jdh-notebook anyway as we neeed to correct the links in the notebook

<img width="652" alt="Screenshot 2021-06-06 at 19 17 18" src="https://user-images.githubusercontent.com/1181642/120933765-d9e9c800-c6fb-11eb-9fef-6e287aeccdba.png">
